### ISSUE TITLE
tag admin boundaries with `data_source` column attribute

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#111]
Think we should tag the admin boundary with a data_source column attribute indicating where it's from. This can then be used in plot caption/legend/annotation. Also will be handy for debugging issues boundaries (ahem NZ).

probably could make sense to incorporate into `download_adm0_sf()` ? 

related to:
https://github.com/OCHA-DAP/hdx-signals/issues/87#issue-2298321368

**Comment by caldwellst** [comment]
Yep, good idea! Could also track if we do or do not use a cities geom in the plot to refer to natural earth.

**Comment by zackarno** [comment]
implementing an approach that could make sense here:
Fixes #115
