### ISSUE TITLE
Viz JRC - legend order

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#130]
Think we should put `Major Hotspot` on top so that severity increases from bottom to top

<img width="114" alt="image" src="https://github.com/OCHA-DAP/hdx-signals/assets/23731112/38b82e10-90e1-4f9d-bbce-1f0eaf47fe4a">

**Comment by caldwellst** [comment]
Yeah good catch! Was previously `Minor hotspot` so autosorted and got lost in the change!
