### ISSUE TITLE
name arg flipped - blob_dev() / blob_wfp() ? 

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#135]
https://github.com/OCHA-DAP/hdx-signals/blob/be124e8e31df76d7127f30f3a5d71e9f9aae1403/src/utils/cloud_storage.R#L214-L239

**Comment by caldwellst** [comment]
Yep, great catch, fixing in my branch now and checking all runs with the new Mailchimp backend!

**Comment by caldwellst** [comment]
Fixed in #132
