### ISSUE TITLE
blob terminology

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#141]
The terminology used in the cloudstorage module is a bit confusing because my understanding is that the `blobs` are the actual files themselves

The hierarchy should be `storage account` -> `container` -> `blob`

https://github.com/OCHA-DAP/hdx-signals/blob/934862b8a6ace590027d3a3e248fdca89842abbd/src/utils/cloud_storage.R#L130-L161

Therefore the `blob_prod()`, `blob_dev()`, and `blob_wfp()` i think should be renamed to `prod_container()`, `dev_container()`, and `wfp_container()`... also `get_blob()` -> `get_container()`

Additionally in functions like `az_file_detect()` i think the `blob` arg should be changed to `container` if that's what it is actually referring to.

if you agree, happy to PR this myself or whatever you think is easier

**Comment by caldwellst** [comment]
Yep agreed! Just quickly changed it from `stage` previously but see now it should just say `container`!
