### ISSUE TITLE
Check legend overlap in maps

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#148]
In some instances, we get legend overlap in maps. 

![](https://mcusercontent.com/ea3f905d50ea939780139789d/images/dd906573-d6f1-28c5-a9c1-04c708ed5a3e.png)

Placement is defined in the assets in `update_iso3_map_settings.R`. We are now no longer using the dynamic sizing for maps (they are all 6x4 inches). It might be worth simply placing the legend at the bottom/top or left/right of a plot rather than placing within the plot for a few countries.

**Comment by caldwellst** [comment]
![image](https://github.com/OCHA-DAP/hdx-signals/assets/8086547/27b4841b-3afa-4d7d-8cbb-c224677b734e)

**Comment by caldwellst** [comment]
Countries with the problem have legends on the inside of the plot, which doesn't work: https://github.com/OCHA-DAP/hdx-signals/blob/main/src-static/update_iso3_map_settings.R#L259. Also would be good to check what is happening in the Somalia example with the numerous white dots.

**Comment by caldwellst** [comment]
I think easiest solution would be that the legend placement is simply vertical and left unless the map has higher than 3/2 width/height ratio.

**Comment by zackarno** [comment]
so what dimensions should we go with for landscape? whats the width limitation?

portrait: 4 x 6 in (w x h)
landscape: ?

**Comment by zackarno** [comment]
ok was misunderstanding -- always landscape:

- 6x4 (wxh) inches.

but i suppose if w/h ration is >3/2 we can still put legend on bottom -- probably a horizontal legend?

**Comment by caldwellst** [comment]
Yep, definitely horizontal! And yes, you got it sorry, meant alternative was bottom and horizontal!
