### ISSUE TITLE
Split up `check_signals_update`?

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#153]
Do we possibly want to split up the code in `src/alerts/check_signals_update.R`? It has functions to check for updates, and then also does the runs. The rest of the code in `src/alerts` (and `src/utils`, `src/images`, `src/email`) are all utilities modules but don't actually do any runs. The only run scripts are in `src/indicators`. So maybe we actually split off `src/indicators` and something else for checking the updates that puts them in a `runs/` folder or something to that effect?

Might be useful if we also build out more functionality to do "approvals" or other parts of the triage process through GitHub, where we would want an R script to run.

**Comment by caldwellst** [comment]
I would like to split these up, now that working a bit on the Slack script. Should we change the directory structure to keep `src`:

1.  move `src/indicators` to `runs/indicators`
2. create a `runs/other` or something where the Slack runs go
3. rename `src-static` to `runs-static`

Thoughts @zackarno @hannahker?

**Comment by martinig94** [comment]
Considering the restructuring performed in #247, we are closing the current issue as not adhering to the current repo structure. Issue #252 poses already the problem of having a different structure with a dedicated 'runs' folder
