### ISSUE TITLE
Update recipients when triaging?

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#161]
When we generate a draft campaign, you have to provide a segment for sending. In between that and triaging, there technically could be additional people signing up. Do we want to refresh the segment at the point in time we approve sending the email? I think would be nice just to avoid awkward questions in these edge cases.

**Comment by hannahker** [comment]
IMO, this would add a reasonable amount of complexity for a pretty rare edge case. Maybe we just have a disclaimer that you may not necessarily receive an alert on the same day that you sign up?

**Comment by caldwellst** [comment]
Honestly, probably just good to leave as is for now, agree about the complexity, and adding to the docs probably just raises more questions than users would actually have (they probably would never think about this).
