### ISSUE TITLE
Add tick marks to represent the exact position on the x-axis

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#180]
A piece of feedback I received from Yakubu from CERF:

> I hope that you are doing good. Thanks once again for the great work on signals. One quick question: could you please look into the possibility of adding tick marks to represent the exact position of the years on the x-axis if it makes sense? 

I think that makes sense for our time series plots! What do y'all think @hannahker @zackarno?

**Comment by zackarno** [comment]
Yea seems like a good point

**Comment by caldwellst** [comment]
Okay, I think we want it for [ACLED](
https://mcusercontent.com/ea3f905d50ea939780139789d/images/1c2752d2-a10e-180f-c74d-ee3226ea8f47.png
), [IDMC](
https://mcusercontent.com/ea3f905d50ea939780139789d/images/815fd87f-c411-fa2f-a293-ea2d660ab16d.png
), and [IPC](
https://mcusercontent.com/ea3f905d50ea939780139789d/images/9c0a48f4-afbb-affb-57a1-254702e700f1.png
).

I don't think it will work for [WFP](https://mcusercontent.com/ea3f905d50ea939780139789d/images/c712830c-1fe6-2feb-2f12-f414fe2199c8.png), and isn't necessary for [JRC](https://mcusercontent.com/ea3f905d50ea939780139789d/images/5a3b69fc-4a11-0f42-cf68-dc9f63ddc138.png).

**Comment by caldwellst** [comment]
Closed by #199
