### ISSUE TITLE
Refinement of `triage_signals` Function: Command Handling, Logging, and Confirmation

### ISSUE THREAD

**Issue by martinig94** [OCHA-DAP/hdx-signals#243]
The `triage_signals` function could benefit from some improvements to enhance its robustness, logging, and user interaction.

**Suggested Improvements:**
- Command Validation: Introduce a DO NOTHING command to exit from the process.
- If an invalid command is provided, the system should recursively ask the user for a valid action instead of proceeding with no action or failing silently.

**Enhanced Logging and console output:**

Add more detailed logging to capture key events and actions within the function. This will help with debugging and provide better context for decisions made during the process. Set proper priority level to be sure to have the needed info as console output

**Double Confirmation for Critical Actions:**

Implement a double confirmation step before performing irreversible actions like approval, deletion, or archiving. This will reduce the risk of accidental actions by requiring explicit user confirmation.

**Why is this important?**
These enhancements would reduce potential errors, provide better visibility into the function’s operations, and make the system more user-friendly by handling incorrect inputs more effectively.

**Impact:**

Improve error handling and system stability.
Provide clearer feedback to users.
Ensure that critical operations are only executed after explicit confirmation.

**Comment by caldwellst** [comment]
Closed by #246
