### ISSUE TITLE
retry GHA run on failure

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#263]
@martinig94 and I were discussing that it would be nice if there was a way for a GHA to re-run 1 or 2x in case of failure. Sometimes certain API fails can call, but then when re-run they work.

Sleuthing around If found this a [retry action](https://github.com/nick-fields/retry) that looks promising.

I tried adding it to the acled_conflict.yaml on the audience-analysis branch as I knew that would fail. I implemented it here:

[2c7e1b0](https://github.com/OCHA-DAP/hdx-signals/pull/253/commits/2c7e1b0d6105d12b1f43f52190713829367b3589)

and here is the [GHA Run](https://github.com/OCHA-DAP/hdx-signals/actions/runs/11941446291) .. it looks like it kind of worked?

anyways i'll probably delete from this `audience-analysis` branch as it is out of scope, but would be nice if we had a sand-box to test this out

**Comment by martinig94** [comment]
hey Zack!
That's cool and I agree that should be done in a separate branch.
I think that the way to test it is to use some sort of mocking, so you can simulate the intended behaviour for the API calls (API not giving a response after the first call and then giving a positive one at the second)
