### ISSUE TITLE
why are there 2 GHA named `lint` ? 

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#265]
One appears to not be linked to a yaml file so we can probably delete it? @martinig94 ?

**Comment by martinig94** [comment]
yes checked a bit the history and deleting the one created by Hannah

**Comment by martinig94** [comment]
@zackarno actually I see that there are also other GHAs thare were run in the past and did not become workflows.
I think we can delete them or at least disable them to have a GHA workspace cleaner. What do you think? Any preference?
I think we could delete them tbh
