### ISSUE TITLE
Add step to notify other users/analysts of GH action run status

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#44]
Looks like GH Action workflow notifications are only sent to user who set the work-flow or whomever last modifies the CRON job. Seems to be a [community discussion](https://github.com/orgs/community/discussions/43415) on this topic with a potential work-around that we might want to consider in this repo and potentially others

**Comment by caldwellst** [comment]
@hannahker Flagging this so you're aware of the issue, might be nice to implement in #80 if not too much work, otherwise for a separate PR.

**Comment by caldwellst** [comment]
Closing in lieu of Slack. Much easier to scale and put all notifications directly in our channel instead of storing everyone's details as secrets on GitHub.
