### ISSUE TITLE
add required env variables to base readme

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#48]
I'd suggest listing all the names of all env vars required in the front readme of the repo.

**Comment by caldwellst** [comment]
None of the README files have been updated, so all documentation will be updated once the actual code is done.

**Comment by hannahker** [comment]
@caldwellst would also advocate for including this as part of a basic "Developer Setup" section, including steps like: 

1. Install R v4.3.3
2. Run `renv::init()` to install packages. Select option to "Restore the project from the lockfile"
3. Set up required env vars in the `.Renviron` file
4. Some explanation of the `GMAS_TEST_RUN` variable (or whatever it ends up being called)

**Comment by caldwellst** [comment]
Agreed! Good ideas.
