### ISSUE TITLE
lockfile not synced with `{magick}` dep

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#51]
Can you add `{magick}` dep to the renv lockfile so I can sync to the correct version?

```
box::use(./utils/plot_displacement)
#> Error in box::use(./utils/plot_displacement) : 
#>   there is no package called ‘magick’
```

writing the tracing below to show that it's getting a bit tricky to trouble shoot simple issues. Would be nice to find the root cause somehow faster or at least be able to double click to jump through files? any suggestions?

1. `src/indicators/idmc_displacement/update_displacement.R` -> `box::use(./utils/plot_displacement)`
2. `src/indicators/idmc_displacement/utils/plot_displacement.R`-> `box::use(../../../images/create_images)`
3. `src/images/create_images.R` -> `box::use(./save_image)`
4. `src/images/save_image.R` -> `box::use(../email/mailchimp/images)`
5. `src/email/maillchimp/images` ->  `box::use(magick)` #final issue!

**Comment by zackarno** [comment]
Actually `renv::status()` returns a bunch of packages in "inconsistent state" for me. So this just means you need to run `renv::snapshot()` i guess i should wait for you to do it so i get the same versions as you instead of visa versa?

**Comment by caldwellst** [comment]
Yeah, just needed to run the `snapshot()`, sorry! Have done now.
