### ISSUE TITLE
idea - `update_adm0_sf()`

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#54]
why not just update this function to create 1 geoparquet file? Then slight modification to the `st_read()` func like below to query the appropriate polygon(s). Would just tighten up the data storage strategy i think

```
sf$st_read(
  dsn = path,
  quiet = T,
  # pseudo-code for query - placeholder "layer_name" and iso3 ("BGD") values
  query="select * from \"layer_name\" where iso3 = 'BGD'"
) 
```

if you think it's a good idea/ i could make an isolated PR or whatever you think is easiest

**Comment by caldwellst** [comment]
I avoided doing that because I figured we would be plagued with geometry errors. Not sure that would actually be the case though, so very happy for you to take it in if you think possible!
