### ISSUE TITLE
`cs` module not loaded in update_country_info.R

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#55]
sort of randomly came across this issue. It seems `cs` module is used, but not loaded in the `update_country_info.R` script

https://github.com/OCHA-DAP/hdx-signals/blob/b4424719e91dd7530cb64b7392d4a404dd7e743b/src-static/update_country_info.R#L128-L131

I wonder if there is a way to quickly/automatically scan the entire repo for this kind of issue as well as circular imports.

**Comment by caldwellst** [comment]
Good catch. I think we should be using precommit here, but last time my R recommit was giving me a lot of trouble. Definitely something we should institute though. Will look into it.

**Comment by caldwellst** [comment]
Fixed.
