### ISSUE TITLE
ocha regions added

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#57]
check [8da515c](https://github.com/OCHA-DAP/hdx-signals/commit/8da515c1f150059170e87aa30426c29a6f6d4302)

added a `mutate()`+ `case_when()` to adjust regions. I've named the new col `ocha_region` for easier comparison, but should be shifted to `region` eventually for it to be integrated into rest of code

**Comment by caldwellst** [comment]
Works perfectly. Thanks a lot, have incorporated fully now!
