### ISSUE TITLE
idmc - wrong api raw_displacement$raw() description

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#61]
not ACLED

https://github.com/OCHA-DAP/hdx-signals/blob/eb4bf8b6b3ec606e6ffcd8c6d3747ab95c07fad9/src/indicators/idmc_displacement/utils/raw_displacement.R#L7

**Comment by caldwellst** [comment]
Ha yes! Thanks. I would refrain from reviewing any of these in detail, still actively developing all of these and then need to go through and check/correct the documentation. Don't want you wasting your time, but thanks for flagging when you do see something! Will post on Slack as I complete modules.
