### ISSUE TITLE
Use Slack notifications to alert when data needs triaging

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#64]
When an indicator run happens and signals are generated, we have to manually triage the campaign and approve it before the email is sent and the data is added to the final file. One way could be to have a Slack channel that gets pinged automatically via the Slack API any time an indicator creates campaign information needing triage. Could use the [`{slackr}`](https://github.com/mrkaye97/slackr) package.

**Comment by hannahker** [comment]
Thinking about edge cases... Should we be concerned at all about amount of manual work required to triage when the permutations between indicators and countries is quite large? I suppose ideally alerts are quite infrequent.
