### ISSUE TITLE
Find method to view local images in HTML preview

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#67]
When developing indicator signals, it's useful to be able to test how the campaign will look, including the content and images. For this, we can run `generate_signals(..., test = TRUE)`. If doing this with `GMAS_TEST_RUN` as `FALSE`, all of the content is still generated and saved to Mailchimp and Azure, and campaigns can even be sent to Mailchimp subscribers tagged as `hdx-signals-test`.

However, if doing this with `GMAS_TEST_RUN` as `TRUE`, all of the templates and imagery are generated locally. The campaign preview is opened up in your default browser using a locally saved HTML file with local links to the images.

The issue is that modern browsers apparently don't actively link to local imagery, see for instance this [SO post](https://stackoverflow.com/questions/28194444/how-can-i-display-an-image-from-the-local-machine-on-a-webpage). Because of this, the images do not appear in the preview. We can still individually open up the local links from the file, or set `GMAS_TEST_RUN` to `FALSE` and test through Mailchimp.

It would be ideal and faster, however, if we could quickly create local previews. So would be good to find a way to make the local imagery appear in the preview. Maybe there is a specific browser for this we could specify as default in `utils$browseURL()`?

**Comment by zackarno** [comment]
> The issue is that modern browsers apparently don't actively link to local imagery, see for instance this [SO post](https://stackoverflow.com/questions/28194444/how-can-i-display-an-image-from-the-local-machine-on-a-webpage). Because of this, the images do not appear in the preview. 

- I see the SO post, but I don't really understand how this could be true because I thought thats and quarto/rmd/bookdown docs do when they are not set to be `self-contained` . Also when designing dashboards in shiny i tend to have local pngs that I display from local when developing.
- Assuming it is true (and perhaps could be good regardless), what if we set set an azure directory to store the test images (and/or maybe non-test images as backup to mailchimp), we then add a column containing these links to the azure files in the parquet table that includes the mailchimp links

**Comment by caldwellst** [comment]
> Also when designing dashboards in shiny i tend to have local pngs that I display from local when developing.

Different from webpages.

> I see the SO post, but I don't really understand how this could be true because I thought thats and quarto/rmd/bookdown docs do when they are not set to be self-contained.

Yeah, so there must be a way that they approach it we can utilise, because we do not want to do any knitting or document creation in these scripts. It seems that the way to workaround the security issue is by only having a [single directory for creation of images within the HTML](https://stackoverflow.com/questions/31886610/add-local-image-file-in-r-presentation).

> Assuming it is true (and perhaps could be good regardless), what if we set set an azure directory to store the test images (and/or maybe non-test images as backup to mailchimp), we then add a column containing these links to the azure files in the parquet table that includes the mailchimp links

I think this is not a good idea because we should have a way to run all the code entirely offline. We basically have two separate ways we can be doing our testing. If `GMAS_TEST_RUN` is `TRUE`, then everything is done locally. And if you run `generate_signals(..., test = TRUE)`, then it tests out creating an email campaign. These arguments are separate from each other, so you can test out email campaigns locally OR in Azure/Mailchimp, and you can do a regular run (`GMAS_TEST_RUN` as `FALSE`) locally or in Mailchimp.

I think for now, to solve the local HTML preview issue, we will need to adjust the scripts to use the same generated `tempdir()`.
