### ISSUE TITLE
Build out documentation in GitBook

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-signals#76]
We want to build out documentation in GitBook. This should be relatively straightforward, but I expect there to be some hiccups. One thing I want to figure out alongside just having all documentation in GitBook is how we can embed some updatable figures in there for specific documentation on things like:

- Geographic coverage of datasets
- Expected frequency of emails based on historic data

I imagine simple enough to setup Rmds for them, and maybe have easy GitHub Actions to update them.

**Comment by hannahker** [comment]
@caldwellst @zackarno check out a dummy site here that I've been playing with: https://chd-1.gitbook.io/sample-docs. See code in [this testing repo](https://github.com/hannahker/sandbox-r).

Things I like about it: 
- It's nice to be able to edit content bi-directionally between `.md` files in the repo and through the Gitbook UI. This means it can be edited/maintained by non-technical folks if we need. 
- If we upgrade to a paid version we can customize the theme to match the Centre's design guidelines.
- You can preview changes in PRs (see https://github.com/hannahker/sandbox-r/pull/2)
- We can set a custom domain. @caldwellst do you know what we'll want this to be?

**Comment by caldwellst** [comment]
This looks so good! Are there limitations on the custom domain for the documentation? Or can it be anything?

What's the process, just basically giving GitHub and GitBook permissions to read to and from each other?

**Comment by hannahker** [comment]
Here's the doc on configuring custom domains: https://docs.gitbook.com/published-documentation/custom-domain/choose -- we just have to own the domain and configure the DNS. 

It's super straightforward to set up! Just created a free account for now and synced it to my testing repo.

**Comment by hannahker** [comment]
Also see the demo [here](https://github.com/hannahker/sandbox-r/blob/main/.github/workflows/create-plots.yml) of how we might update figures that are embedded in the docs. I like that the output of this [creates a PR](https://github.com/hannahker/sandbox-r/pull/3) with the new figure, which also gives us the ability to preview the updated figure in the staging docs before merging.

**Comment by caldwellst** [comment]
That is such a cool way to update the graphs. I love it. Let's go ahead and use Gitbook! Gonna ask Leonardo.
