### ISSUE TITLE
where is un_geodata.geojson initially created?

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#88]
where is `un_geodata.geojson` initially created? I can't seem to find it

**Comment by hannahker** [comment]
@caldwellst is it [this file](https://geoportal.un.org/arcgis/home/item.html?id=d7caaff3ef4b4f7c82689b7c4694ad92)?

**Comment by caldwellst** [comment]
Yes, that's it!

**Comment by hannahker** [comment]
Hmm do you see a way that we could download this programmatically? I'm just seeing a manual download button

**Comment by caldwellst** [comment]
No, that's why I just manually downloaded. Is there a way to access via web services @zackarno? I'm not too familiar with that kinda map data provision.

**Comment by caldwellst** [comment]
This needs to be added to our documentation!

**Comment by caldwellst** [comment]
Still needs to be documented all of these files, will put in `src-static`. Note also that I've added a new manually procured geojson with complex boundaries in #178.
