### ISSUE TITLE
Apply data protection rules for Azure container

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/hdx-signals#91]
- [x] Soft delete for blobs
- [ ] Versioning for blobs 

See: https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-enable?tabs=portal

I have access through the UI for soft delete, but not for versioning. @caldwellst do you know who we reach out to for this?

**Comment by caldwellst** [comment]
It would be Saeid again!

**Comment by caldwellst** [comment]
How's this going?

**Comment by hannahker** [comment]
@caldwellst soft delete is enabled with 7 days recovery. Apparently the type of storage account we have (Delta Lake Storage) does not allow blob versioning... I can look into this further and see if there are any options to change this.

**Comment by caldwellst** [comment]
Okay weird! If not, we could maybe setup manual copying on the overall file to another folder every time we are going to overwrite?

**Comment by hannahker** [comment]
Done. Blob versioning is not supported for our container type (Delta Lake). See #193 for next steps.
